### ISSUE TITLE
No module named 'video_plotting'

### ISSUE THREAD

**Issue by joshikaustubh** [Igorsmit00/DRL-Guided-Picker-Optimization#1]
Hello,

I am trying to test out this code. I am unable to locate the video_plotting module to run this code.

Here are the steps I followed:

1) Cloned the repository
2) Installed required packages
3) Ran 'ppo_training_run_mo_env.py'

I am using it on a MacOS if that helps. Kindly let me know what can be done.

Thanks!

**Comment by Igorsmit00** [comment]
Hi,

Thank you for your interest in our work! I see that we had a wrong import statement. I adjusted it and it should now correctly import the required function. I hope this helps. Feel free to let me know if everything works well now!

Igor.

**Comment by joshikaustubh** [comment]
Thanks a lot, it worked great!
